### ISSUE TITLE
Exception message when using Fiji (fluorescent ISH)

### ISSUE THREAD

**Issue by kingdim-nih** [andmccall/Colocalization_by_Cross_Correlation#10]
Hello,
I am a student working at NIH and I am trying to use your “Colocalization by Cross Correlation” plugin. I have some images stained with fluorescence in situ hybridization (RNAscope) and I am trying to see the spatial separation between the expression of two genes. I believe I have followed all the instructions online, but I keep getting this exception message no matter what I try (attached). Please let me know if you have any idea what the issue might be.
 
Thank you for your time!
 
Diana

(Fiji Is Just) Image) 2.14.0/1.54f; Java 1.8.0_322 [64-bit]; Mac OS X 10.16; 204MB of 8889MB (2%)
java.lang.ClassCastException: net.imglib2.type.numeric.integer.UnsignedByteType cannot be cast to net.imglib2.RandomAccess at net.imglib2.loops.FastCursorLoopsSOneCursorLoop.accept(FastCursorLoops.java:126)
at net.imglib2.loops.LoopBuilder.lambdaSrunOnChunkUsingCursors$5(LoopBuilder.java:401)
at net.imglib2.loops.LoopBuilder.lambda$forEachPixel$O(LoopBuilder.java:159)
at net.imglib2.loops.LoopBuilder.runOnChunkUsingCursors(LoopBuilder.java:399)
at net.imglib2.loops.LoopBuilder.lambdaSrunUsingCursors$4(LoopBuilder.java:391)
at net.imglib2.parallel.DefaultTaskExecutor.lambdaSforEachApplyS1(DefaultTaskExecutor.java:118)
at java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(ForkJoinTask.java:1424)
at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
at java.util.concurrent.ForkJoinTask.dolnvoke(ForkJoinTask.java:401)
at java.util.concurrent.ForkJoinTask.invokeAllForkJoinTask.java:843)
at net.imglib2.parallel.ForkJoinExecutorService.invokeAlI(ForkJoinExecutorService.java:126)
at net.imglib2.parallel.DefaultTaskExecutor.forEachApply(DefaultTaskExecutor.java:121)
at net.imglib2.loops.LoopBuilder.runUsingCursors(LoopBuilder.java:390)
at net.imglib2.loops.LoopBuilder.forEachChunk(LoopBuilder.java:197)
at net.imglib2.loops.LoopBuilder.forEachPixel(LoopBuilder.java:158)
at CostesRandomizer.populateBlockList(CostesRandomizer.java:43)
at CostesRandomizer.<init>(CostesRandomizer.java:24)
at Colocalization_by_Cross_Correlation.run(Colocalization_by_Cross_Correlation.java:72)
at ij.lJ.runUserPlugIn(UJ.java:244)
at ij.j.runPlugIn(IJ.java:210)
at ij.Executer.runCommand(Executer.java:152)
at ij.Executer.run(Executer.java: 70)
at java.lang.Thread.run(Thread.java:750)

**Comment by andmccall** [comment]
Worked with Diana to fix the issue
